package gogen

import (
	"regexp"
	"strings"
	"text/template"
)

const KGeneratedFileWarningComment = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// {{.Timestamp}}
`

var (
	MatchGoFile = regexp.MustCompile("(.)\\.go$")
	FuncMap = template.FuncMap{
		"ToLower": strings.ToLower,
	}
)
