package gogen

const kInterfaceTpl = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// {{ .Timestamp }}
package {{.Package}}

type {{.Type}}Repository interface {
    GetInsertFields() []string
    GetInsertValues({{.Type}}) []interface{}
    GetSelectDestinations({{.Type}}) []interface{}
    GetSelectFields(alias string) []string
    GetUpdateFields() []string
    GetUpdateValues({{.Type}}) []interface{}
}
`

const kImplementationTpl = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// {{ .Timestamp }}
package sql

import "{{ .ModelPackage }}"

type {{.Type}} struct {}

func (r {{.Type}}) GetInsertFields(alias string) []string {
    a := alias
    if a != "" {
        a += "."
    }
    return []string{ {{ range .InsertFields }}a+"{{ . }}",{{ end }} }
}

func (r {{.Type}}) GetInsertValues(m {{ .ModelPackage }}.{{ .Type }}) []interface{} {
    return []interface{}{ {{ range .InsertValues }}m.{{ . }},{{ end }} }
}

func (r {{.Type}}) GetSelectFields(alias string) []string {
    a := alias
    if a != "" {
        a += "."
    }
    return []string{ {{ range .SelectFields }}a+"{{ . }}",{{ end }} }
}
`